Had to make a small change to how the category checkboxes are created on the item search page. Changing from Django 4.0.6 to 4.2.16 seems to have changed something in how annotate and window functions interact.
Setup for both examples.

```
python manage.py shell_plus
>>> from django.db import models
```

This version runs and returns a record for each category with the line item count and a sequential number.
Django version 4.0.6

```
>>> print(inv_models.SourceItem.objects.values('source_category').annotate(line_items=models.Count('id'),row_number=models.expressions.Window(expression=models.functions.RowNumber(), order_by=models.F('source_category').asc())).order_by('source_category').query)
SELECT
    "inventory_sourceitem"."source_category",
    COUNT("inventory_sourceitem"."id") AS "line_items",
    ROW_NUMBER() OVER (ORDER BY "inventory_sourceitem"."source_category" ASC) AS "row_number"
FROM "inventory_sourceitem"
GROUP BY "inventory_sourceitem"."source_category"
ORDER BY "inventory_sourceitem"."source_category" ASC
```

This version fails.  The only difference in the generated sql is the `, 3` in the `GROUP BY` clause.

```
psycopg2.errors.WindowingError: window functions are not allowed in GROUP BY
LINE 1: ...UNT("inventory_sourceitem"."id") AS "line_items", ROW_NUMBER...
... snip ...
django.db.utils.ProgrammingError: window functions are not allowed in GROUP BY
LINE 1: ...UNT("inventory_sourceitem"."id") AS "line_items", ROW_NUMBER...
```

Django version 4.2.16

```
>>> print(inv_models.SourceItem.objects.values('source_category').annotate(line_items=models.Count('id'),row_number=models.expressions.Window(expression=models.functions.RowNumber(), order_by=models.F('source_category').asc())).order_by('source_category').query)
SELECT
    "inventory_sourceitem"."source_category",
    COUNT("inventory_sourceitem"."id") AS "line_items",
    ROW_NUMBER() OVER (ORDER BY "inventory_sourceitem"."source_category" ASC) AS "row_number"
FROM "inventory_sourceitem"
GROUP BY "inventory_sourceitem"."source_category", 3
ORDER BY "inventory_sourceitem"."source_category" ASC
```