Having a hard time getting unit tests running.  Either getting the following with code as is: RuntimeError: Model class apps.inventory.models.category.Category doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
Or, after adding app_label to Category, getting:
RuntimeError: Conflicting 'category' models in application 'inventory': <class 'inventory.models.category.Category'> and <class 'apps.inventory.models.category.Category'>.

Trying to find solutions on Google just keep claiming the app is missing from settings.py which is not the case here.